spring.datasource.url=jdbc:postgresql://localhost:5432/atlashr
spring.datasource.username=postgres
spring.datasource.password=your_password_here
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=phmZF7/esaVqZuONpGaDe10WnFhdE2wxyUWrzwt//azt4vjvAmo+VqUIi/oOuyZO
jwt.expiration=86400000